import type { I18nDict } from '../i18n/types';

export const en: I18nDict = {
  header: {
    cave: 'Cave',
    manifesto: 'Manifesto',
    ancient: 'Ancient',
    exit: 'Exit',
    team: 'Creators',
    events: 'Events',
    natureUrban: 'Nature→Urban',
    gallery: 'Gallery',
    contact: 'Contact',
    movie: 'Documentary',
    brandHint: 'Art of Creation',
    viewAsList: 'Enter the Archive',
  },
  cave: {
    title: 'Lingua Universalis',
    subtitle: 'The Art of Creation',
    manifestoTitle: 'Manifesto',
    manifesto: [
      'Art is humanity’s first word—\na silent, eternal language that precedes all borders\nand spoken tongues.',
      'Creation is not the pursuit of the "new,"\nbut a ritual to recover the "real"—\nreconnecting the soul to the cosmos.',
      'Beyond modern fragmentation,\nthe Art of Creation acts as a bridge,\nweaving together the threads of our collective consciousness.',
      'The prehistoric and the futuristic\nare two ends of the same path—\nto look back at our origins is to trace the blueprint of our future.',
      'Thousands of years ago,\nwe began a conversation on the walls.\nThat conversation has never ended.',
    ],
    flashlightTitle: 'Flashlight',
    flashlightHint: 'Move the cursor to reveal the cave.',
    flashlightHint2: 'Scroll down—the journey begins.',
    breachLabel: 'Enter\nThe archive',
    breachDesc: 'Direct access to the results.\nView the portfolio and events',
    artifacts: [
      { title: 'Carnarvon Gorge', location: 'Australia' },
      { title: 'Chauvet Cave', location: 'France' },
      { title: "Bunjil's Shelter", location: 'Australia' },
      { title: 'Xique-Xique 1', location: 'Brazil' },
    ],
  },
  ancient: { title: 'Ancient marks' },
  exitFlight: {
    title: 'Exit',
    hint: 'Scroll to pass through the opening.',
  },
  team: { title: 'Creators', subtitle: 'Project Team', hint: 'Hover/focus to pause and read.', pause: 'Pause' },
  events: { title: 'Events', hint: 'Hover/focus to pause. Scroll to continue.', pause: 'Pause', explore: 'Explore', scrollDiscover: 'Scroll to Discover' },
  gallery: {
    title: 'Works Gallery',
    lede: 'Search, filter by artist, and open a work. The URL becomes shareable for that work.',
    searchPlaceholder: 'Search by artist / title…',
    artistFilterAll: 'All artists',
    sortArtist: 'Artist A→Z',
    sortTitle: 'Title A→Z',
    lightboxPrev: 'Prev',
    lightboxNext: 'Next',
    lightboxClose: 'Close',
  },
  natureUrban: {
    title: 'Nature → Urban',
    lede: 'A journey from primal origins to the architecture of the future.',
  },
  contact: {
    title: 'Signal',
    subtitle: 'Establish connection through the universal frequency.',
    coreHint: 'Click the Core to open the transmitter',
    formName: 'Your Name',
    formEmail: 'Your Email',
    formMessage: 'Your Message',
    formSubmit: 'Send Signal',
    sending: 'Transmitting...',
    success: 'Signal Transmitted. Connection established.',
    error: 'Frequency interference. Please try again.',
    back: 'Back',
  },
};


