import type { I18nDict } from '../i18n/types';

export const en: I18nDict = {
  header: {
    cave: 'Cave',
    manifesto: 'Manifesto',
    ancient: 'Ancient',
    exit: 'Exit',
    team: 'Creators',
    events: 'Events',
    natureUrban: 'Nature→Urban',
    gallery: 'Gallery',
    contact: 'Contact',
    movie: 'Documentary',
    brandHint: 'Art of Creation',
    viewAsList: 'Back to Source',
    backToArchive: 'Back to Source',
    journeyToWorld: 'The journey to Lingua Universalis world',
  },
  cave: {
    title: 'Lingua Universalis',
    subtitle: 'The Art of Creation',
    manifestoTitle: 'Manifesto',
    manifesto: [
      'Art is humanity’s first word—\na silent, eternal language that precedes\nall borders and spoken tongues.',
      'Creation is not the pursuit of the "new," but a ritual\nto recover the "real"—reconnecting the soul\nto the cosmos.',
      'Beyond modern fragmentation, the Art of Creation acts\nas a bridge, weaving together the threads\nof our collective consciousness.',
      'The aesthetic of the project is a bridge\nbetween the prehistoric and the meta-modern:\npast and future at once.',
      'Thousands of years ago, we began\na conversation on the walls.\nThat conversation has never ended.',
    ],
    flashlightTitle: 'Flashlight',
    flashlightHint: 'Move the cursor to reveal the cave.',
    flashlightHint2: 'Scroll down—the journey begins.',
    breachLabel: 'Back to\nSource',
    breachDesc: 'Direct access to the results.\nView the portfolio and events',
    artifacts: [
      { title: 'Carnarvon Gorge', location: 'Australia' },
      { title: 'Chauvet Cave', location: 'France' },
      { title: "Bunjil's Shelter", location: 'Australia' },
      { title: 'Xique-Xique 1', location: 'Brazil' },
    ],
  },
  ancient: { title: 'Ancient marks' },
  exitFlight: {
    title: 'Exit',
    hint: 'Scroll to pass through the opening.',
  },
  team: { title: 'Creators', subtitle: 'Project Team', hint: 'Hover/focus to pause and read.', pause: 'Pause' },
  events: { title: 'Events', hint: 'Hover/focus to pause. Scroll to continue.', pause: 'Pause', explore: 'Explore', scrollDiscover: 'Scroll to Discover' },
  gallery: {
    title: 'Works Gallery',
    subtitle: 'LINGUA UNIVERSALIS ARCHIVE',
    portalLabel: 'Start the journey',
    intro: 'The world of Lingua Universalis is a space where boundaries and time disappear. The code of our unity is encrypted in every image.',
    lede: 'Search, filter by artist, and open a work. The URL becomes shareable for that work.',
    searchPlaceholder: 'Search by artist / title…',
    artistFilterAll: 'All artists',
    sortArtist: 'Artist A→Z',
    sortTitle: 'Title A→Z',
    lightboxPrev: 'Prev',
    lightboxNext: 'Next',
    lightboxClose: 'Close',
  },
  natureUrban: {
    title: 'Nature → Urban',
    lede: 'A journey from primal origins to the architecture of the future.',
  },
  contact: {
    title: 'Signal',
    subtitle: 'Establish connection through the universal frequency.',
    coreHint: 'Click the Core to open the transmitter',
    formName: 'Your Name',
    formEmail: 'Your Email',
    formMessage: 'Your Message',
    formSubmit: 'Send Signal',
    sending: 'Transmitting...',
    success: 'Signal Transmitted. Connection established.',
    error: 'Frequency interference. Please try again.',
    back: 'Back',
  },
  declaration: {
    title: 'PROJECT DECLARATION',
    projectTitle: '«LINGUA UNIVERSALIS. THE ART OF CREATION»',
    projectDescription: 'The project "Lingua universalis. The Art of Creation" presents works of art in various fields (painting, sculpture, digital art) by professional artists from Cuba, Venezuela, Armenia, Spain, as well as their Russian colleagues.',
    goalTitle: 'The goal of the project:',
    goalDescription: 'to draw attention to the fact that the language of art, being the most ancient, universal and understandable to every person on the planet, is used today, as a rule, for utilitarian purposes: in the field of propaganda, design, etc. to extract commercial profit, while ignoring its immeasurably wider possibilities. Possessing a universal ability to penetrate into spiritual spheres, art should fully become a tool for exploring man, his relationship with the Universe, and, ultimately, meeting with oneself. Today it is a matter of survival of human civilization.',
    fragmentationTitle: 'Fragmentation and Tension',
    fragmentationDescription: 'The modern world has reached the zenith of fragmentation and tension. At the same time, we see a trend among a number of countries and peoples towards rapprochement, however, real rapprochement of different cultures is possible only on the basis of a common language, which is art, as well as awareness of a common past conditioned by a single origin of man. Art, at the same time, must be pure, devoid of the pressure of commercial platforms and structures that dictate their will to the artist. Such pure independent art, we call the Art of Creation.',
    artistsTitle: 'Artists',
    artistsDescription: 'Joslen Orsini, Marichel Rodes, Peter Tsvetkov, Evgeny Globenko, Omar Godinez, Tomas Arutyunyan, Andrey Vaganov present their works filled with spiritual quests, interesting solutions for their plastic embodiment.',
    visitDescription: 'By visiting the exhibition "Lingua universalis. The Art of Creation", the viewer will be surprised to find how original and, at the same time, close in spirit to Russians are the works of modern masters whose creativity originated many thousands of kilometers from Moscow.',
    messageDescription: 'The participants view this project as a message to young people on all continents, because the world they will live in depends on their choice.',
  },
};


