import type { I18nDict } from '../i18n/types';

export const es: I18nDict = {
  header: {
    cave: 'Cueva',
    manifesto: 'Manifiesto',
    ancient: 'Marcas antiguas',
    exit: 'Salida',
    team: 'Creadores',
    events: 'Eventos',
    natureUrban: 'Naturaleza→Urbano',
    gallery: 'Galería',
    contact: 'Contacto',
    movie: 'Documental',
    brandHint: 'El Arte de la Creación',
    viewAsList: 'Entrar al archivo',
  },
  cave: {
    title: 'Lingua Universalis',
    subtitle: 'El Arte de la Creación',
    manifestoTitle: 'Manifiesto',
    manifesto: [
      'El arte es la primera palabra de la humanidad:\nun lenguaje silencioso y eterno que precede a toda frontera\ny lengua hablada.',
      'La creación no es la búsqueda de lo "nuevo",\nsino un ritual para recuperar lo "real",\nreconectando el alma con el cosmos.',
      'Más allá de la fragmentación moderna,\nel Arte de la Creación actúa como un puente,\nentrelazando los hilos de nuestra conciencia colectiva.',
      'Lo prehistórico y lo futurista\nson los dos extremos de un mismo camino:\nmirar hacia nuestros orígenes es descubrir el plano de nuestro futuro.',
      'Hace milenios, comenzamos una conversación en los muros.\nUn diálogo que nunca se ha detenido.',
    ],
    flashlightTitle: 'Linterna',
    flashlightHint: 'Mueve el cursor para revelar la cueva.',
    flashlightHint2: 'Desplázate hacia abajo: el viaje comienza.',
    breachLabel: 'Entrar al\narchivo',
    breachDesc: 'Acceso directo a los resultados.\nVer el portafolio y eventos',
    artifacts: [
      { title: 'Desfiladero de Carnarvon', location: 'Australia' },
      { title: 'Cueva de Chauvet', location: 'Francia' },
      { title: 'Refugio de Bunjil', location: 'Australia' },
      { title: 'Xique-Xique 1', location: 'Brasil' },
    ],
  },
  ancient: { title: 'Marcas antiguas' },
  exitFlight: {
    title: 'Salida',
    hint: 'Desplázate para pasar por la abertura.',
  },
  team: { title: 'Creadores', subtitle: 'Equipo del Proyecto', hint: 'Pasa el cursor para pausar y leer.', pause: 'Pausa' },
  events: { title: 'Eventos', hint: 'Pasa el cursor para pausar. Desplázate para continuar.', pause: 'Pausa', explore: 'Explorar', scrollDiscover: 'Desplázate para descubrir' },
  gallery: {
    title: 'Galería de Obras',
    lede: 'Busca, filtra por artista y abre una obra. La URL se vuelve compartible para esa obra.',
    searchPlaceholder: 'Buscar por artista / título...',
    artistFilterAll: 'Todos los artistas',
    sortArtist: 'Artista A→Z',
    sortTitle: 'Título A→Z',
    lightboxPrev: 'Anterior',
    lightboxNext: 'Siguiente',
    lightboxClose: 'Cerrar',
  },
  natureUrban: {
    title: 'Naturaleza → Urbano',
    lede: 'Un viaje desde los orígenes primordiales hasta la arquitectura del futuro.',
  },
  contact: {
    title: 'Señal',
    subtitle: 'Establece conexión a través de la frecuencia universal.',
    coreHint: 'Haz clic en el Núcleo para abrir el transmisor',
    formName: 'Tu nombre',
    formEmail: 'Tu correo electrónico',
    formMessage: 'Tu mensaje',
    formSubmit: 'Enviar señal',
    sending: 'Transmitiendo...',
    success: 'Señal transmitida. Conexión establecida.',
    error: 'Interferencia de frecuencia. Por favor, inténtalo de nuevo.',
    back: 'Volver',
  },
};
