import type { I18nDict } from '../i18n/types';

export const es: I18nDict = {
  header: {
    cave: 'Cueva',
    manifesto: 'Manifiesto',
    ancient: 'Marcas antiguas',
    exit: 'Salida',
    team: 'Creadores',
    events: 'Eventos',
    natureUrban: 'Naturaleza→Urbano',
    gallery: 'Galería',
    contact: 'Contacto',
    movie: 'Documental',
    brandHint: 'El Arte de la Creación',
    viewAsList: 'Volver al Origen',
    backToArchive: 'Volver al Origen',
    journeyToWorld: 'El viaje al mundo de Lingua Universalis',
  },
  cave: {
    title: 'Lingua Universalis',
    subtitle: 'El Arte de la Creación',
    manifestoTitle: 'Manifiesto',
    manifesto: [
      'El arte es la primera palabra de la humanidad:\nun lenguaje silencioso y eterno que precede a toda\nfrontera y lengua hablada.',
      'La creación no es la búsqueda de lo "nuevo", sino\nun ritual para recuperar lo "real", reconectando\nel alma con el cosmos.',
      'Más allá de la fragmentación moderna, el Arte\nde la Creación actúa como un puente, entrelazando\nlos hilos de nuestra conciencia colectiva.',
      'La estética del proyecto constituye un puente\nentre lo prehistórico y lo metamoderno: pasado\ny futuro a la vez.',
      'Hace milenios, comenzamos una conversación\nen los muros. Un diálogo que nunca se ha detenido.',
    ],
    flashlightTitle: 'Linterna',
    flashlightHint: 'Mueve el cursor para revelar la cueva.',
    flashlightHint2: 'Desliza para comenzar',
    breachLabel: 'Volver\nal Origen',
    breachDesc: 'Acceso directo a los resultados.\nVer el portafolio y eventos',
    artifacts: [
      { title: 'Desfiladero de Carnarvon', location: 'Australia' },
      { title: 'Cueva de Chauvet', location: 'Francia' },
      { title: 'Refugio de Bunjil', location: 'Australia' },
      { title: 'Xique-Xique 1', location: 'Brasil' },
    ],
  },
  ancient: { title: 'Marcas antiguas' },
  exitFlight: {
    title: 'Salida',
    hint: 'Baja para pasar por la abertura.',
  },
  team: { title: 'Creadores', subtitle: 'Equipo del Proyecto', hint: 'Pasa el cursor para pausar y leer.', pause: 'Pausa' },
  events: { title: 'Eventos', hint: 'Pasa el cursor para pausar. Desplázate para continuar.', pause: 'Pausa', explore: 'Explorar', scrollDiscover: 'Baja para descubrir' },
  gallery: {
    title: 'Galería de Obras',
    subtitle: 'ARCHIVO LINGUA UNIVERSALIS',
    portalLabel: 'Comenzar el viaje',
    intro: 'El mundo de Lingua Universalis es un espacio donde las fronteras y el tiempo desaparecen. El código de nuestra unidad está encriptado en cada imagen.',
    lede: 'Busca, filtra por artista y abre una obra. La URL se vuelve compartible para esa obra.',
    searchPlaceholder: 'Buscar por artista / título...',
    artistFilterAll: 'Todos los artistas',
    sortArtist: 'Artista A→Z',
    sortTitle: 'Título A→Z',
    lightboxPrev: 'Anterior',
    lightboxNext: 'Siguiente',
    lightboxClose: 'Cerrar',
  },
  natureUrban: {
    title: 'Naturaleza → Urbano',
    lede: 'Un viaje desde los orígenes primordiales hasta la arquitectura del futuro.',
  },
  contact: {
    title: 'Señal',
    subtitle: 'Establece conexión a través de la frecuencia universal.',
    coreHint: 'Haz clic en el Núcleo para abrir el transmisor',
    formName: 'Tu nombre',
    formEmail: 'Tu correo electrónico',
    formMessage: 'Tu mensaje',
    formSubmit: 'Enviar señal',
    sending: 'Transmitiendo...',
    success: 'Señal transmitida. Conexión establecida.',
    error: 'Interferencia de frecuencia. Por favor, inténtalo de nuevo.',
    back: 'Volver',
  },
  declaration: {
    title: 'DECLARACIÓN DEL PROYECTO',
    projectTitle: '«LINGUA UNIVERSALIS. EL ARTE DE LA CREACIÓN»',
    projectDescription: 'El proyecto "Lingua universalis. El Arte de la Creación" presenta obras de arte en diversos campos (pintura, escultura, arte digital) de artistas profesionales de Cuba, Venezuela, Armenia, España, así como de sus colegas rusos.',
    goalTitle: 'El objetivo del proyecto:',
    goalDescription: 'llamar la atención sobre el hecho de que el lenguaje del arte, siendo el más antiguo, universal y comprensible para cada persona en el planeta, se utiliza hoy en día, por regla general, para fines utilitarios: en el campo de la propaganda, el diseño, etc., para obtener beneficios comerciales, ignorando sus posibilidades inmensamente más amplias. Al poseer una capacidad universal para penetrar en las esferas espirituales, el arte debe convertirse plenamente en una herramienta para explorar al hombre, su relación con el Universo y, en última instancia, el encuentro con uno mismo. Hoy en día es una cuestión de supervivencia de la civilización humana.',
    fragmentationTitle: 'Fragmentación y Tensión',
    fragmentationDescription: 'El mundo moderno ha alcanzado el cenit de la fragmentación y la tensión. Al mismo tiempo, vemos una tendencia en varios países y pueblos hacia el acercamiento; sin embargo, el verdadero acercamiento de las diferentes culturas solo es posible sobre la base de un lenguaje común, que es el arte, así como la conciencia de un pasado común condicionado por un origen único del hombre. El arte, al mismo tiempo, debe ser puro, libre de la presión de las plataformas y estructuras comerciales que dictan su voluntad al artista. A este arte puro e independiente lo llamamos el Arte de la Creación.',
    artistsTitle: 'Artistas',
    artistsDescription: 'Joslen Orsini, Marichel Rodes, Peter Tsvetkov, Evgeny Globenko, Omar Godinez, Tomas Arutyunyan, Andrey Vaganov presentan sus obras llenas de búsquedas espirituales e interesantes soluciones para su encarnación plástica.',
    visitDescription: 'Al visitar la exposición "Lingua universalis. El Arte de la Creación", el espectador se sorprenderá al descubrir cuán originales y, al mismo tiempo, cercanos en espíritu a los rusos son las obras de los maestros modernos cuya creatividad se originó a muchos miles de kilómetros de Moscú.',
    messageDescription: 'Los participantes ven este proyecto como un mensaje a los jóvenes de todos los continentes, porque el mundo en el que vivirán depende de su elección.',
  },
};
