import type { I18nDict } from '../i18n/types';

export const es: I18nDict = {
  header: {
    cave: 'Cueva',
    manifesto: 'Manifiesto',
    ancient: 'Marcas antiguas',
    exit: 'Salida',
    team: 'Creadores',
    events: 'Eventos',
    natureUrban: 'Naturaleza→Urbano',
    gallery: 'Galería',
    contact: 'Contacto',
    movie: 'Documental',
    brandHint: 'El Arte de la Creación',
    viewAsList: 'Entrar al archivo',
  },
  cave: {
    title: 'Lingua Universalis',
    subtitle: 'El Arte de la Creación',
    manifestoTitle: 'Manifiesto',
    manifesto: [
      'El lenguaje del arte es la forma de comunicación más antigua, universal y comprensible de la Tierra.',
      'El arte es un instrumento para explorar la condición humana y nuestra relación con el Universo.',
      'En una era de fragmentación, el Arte de la Creación se convierte en una base para el entendimiento mutuo: un puente entre culturas.',
      'La estética es un puente entre lo prehistórico y lo metamoderno: antiguo y futurista a la vez.',
      'La verdad está oculta en la oscuridad: el conocimiento se revela solo cuando el espectador aporta enfoque: la Luz.',
    ],
    flashlightTitle: 'Linterna',
    flashlightHint: 'Mueve el cursor para revelar la cueva.',
    flashlightHint2: 'Desplázate hacia abajo: el viaje comienza.',
    breachLabel: 'Entrar al\narchivo',
    breachDesc: 'Acceso directo a los resultados.\nVer el portafolio y eventos',
  },
  ancient: { title: 'Marcas antiguas' },
  exitFlight: {
    title: 'Salida',
    hint: 'Desplázate para pasar por la abertura.',
  },
  team: { title: 'Creadores (constelación)', hint: 'Pasa el cursor para pausar y leer.', pause: 'Pausa' },
  events: { title: 'Eventos', hint: 'Pasa el cursor para pausar. Desplázate para continuar.', pause: 'Pausa', explore: 'Explorar', scrollDiscover: 'Desplázate para descubrir' },
  gallery: {
    title: 'Galería de Obras',
    lede: 'Busca, filtra por artista y abre una obra. La URL se vuelve compartible para esa obra.',
    searchPlaceholder: 'Buscar por artista / título...',
    artistFilterAll: 'Todos los artistas',
    sortArtist: 'Artista A→Z',
    sortTitle: 'Título A→Z',
    lightboxPrev: 'Anterior',
    lightboxNext: 'Siguiente',
    lightboxClose: 'Cerrar',
  },
  natureUrban: {
    title: 'Naturaleza → Urbano',
    lede: 'Un viaje desde los orígenes primordiales hasta la arquitectura del futuro.',
  },
  contact: {
    title: 'Señal',
    subtitle: 'Establece conexión a través de la frecuencia universal.',
    coreHint: 'Haz clic en el Núcleo para abrir el transmisor',
    formName: 'Tu nombre',
    formEmail: 'Tu correo electrónico',
    formMessage: 'Tu mensaje',
    formSubmit: 'Enviar señal',
    sending: 'Transmitiendo...',
    success: 'Señal transmitida. Conexión establecida.',
    error: 'Interferencia de frecuencia. Por favor, inténtalo de nuevo.',
    back: 'Volver',
  },
};
