export type GalleryWork = {
  id: string;
  artist: string;
  titleEn: string;
  titleRu: string;
  titleEs: string;
  src: string;
  tags: string[];
  year?: string;
  size?: string;
  mediumEn?: string;
  mediumRu?: string;
  mediumEs?: string;
};

const enc = (path: string) => encodeURI(path);

export const galleryWorks: GalleryWork[] = [
  {
    id: 'andreyvaganov-breathofnature',
    artist: 'Andrey Vaganov',
    titleEn: 'Breath of Nature',
    titleRu: 'Дыхание природы',
    titleEs: 'Aliento de la naturaleza',
    src: enc('/assets/gallery/AndreyVaganov_BreathofNature.jpg'),
    tags: ['andreyvaganov'],
    year: '2024',
    size: '100×100 cm',
    mediumEn: 'Digital Art',
    mediumRu: 'Цифровое искусство',
    mediumEs: 'Arte digital',
  },
  {
    id: 'andreyvaganov-tellings',
    artist: 'Andrey Vaganov',
    titleEn: 'Tellings',
    titleRu: 'Сказания',
    titleEs: 'Relatos',
    src: enc('/assets/gallery/AndreyVaganov_Tellings.jpg'),
    tags: ['andreyvaganov'],
    year: '2024',
    size: '80×100 cm',
    mediumEn: 'Digital Art',
    mediumRu: 'Цифровое искусство',
    mediumEs: 'Arte digital',
  },
  {
    id: 'andreyvaganov-thepath',
    artist: 'Andrey Vaganov',
    titleEn: 'The Path',
    titleRu: 'Путь',
    titleEs: 'El camino',
    src: enc('/assets/gallery/AndreyVaganov_ThePath.jpg'),
    tags: ['andreyvaganov'],
    year: '2024',
    size: '120×80 cm',
    mediumEn: 'Digital Art',
    mediumRu: 'Цифровое искусство',
    mediumEs: 'Arte digital',
  },
  {
    id: 'andreyvaganov-theunityoftheuniverse',
    artist: 'Andrey Vaganov',
    titleEn: 'The Unity of The Universe',
    titleRu: 'Единство вселенной',
    titleEs: 'La unidad del universo',
    src: enc('/assets/gallery/AndreyVaganov_TheUnityofTheUniverse.jpg'),
    tags: ['andreyvaganov'],
    year: '2024',
    size: '150×120 cm',
    mediumEn: 'Digital Art',
    mediumRu: 'Цифровое искусство',
    mediumEs: 'Arte digital',
  },
  {
    id: 'evgenyglobenko-1',
    artist: 'Evgeny Globenko',
    titleEn: 'Void Fragment I',
    titleRu: 'Фрагмент пустоты I',
    titleEs: 'Fragmento del vacío I',
    src: enc('/assets/gallery/EvgenyGlobenko_1.jpg'),
    tags: ['evgenyglobenko'],
    year: '2024',
    size: '70×70 cm',
    mediumEn: 'Oil',
    mediumRu: 'Холст, масло',
    mediumEs: 'Óleo',
  },
  {
    id: 'evgenyglobenko-2',
    artist: 'Evgeny Globenko',
    titleEn: 'Void Fragment II',
    titleRu: 'Фрагмент пустоты II',
    titleEs: 'Fragmento del vacío II',
    src: enc('/assets/gallery/EvgenyGlobenko_2.jpg'),
    tags: ['evgenyglobenko'],
    year: '2024',
    size: '60×80 cm',
    mediumEn: 'Oil',
    mediumRu: 'Холст, масло',
    mediumEs: 'Óleo',
  },
  {
    id: 'evgenyglobenko-cup-of-silence',
    artist: 'Evgeny Globenko',
    titleEn: 'Cup of Silence',
    titleRu: 'Чаша тишины',
    titleEs: 'Copa de silencio',
    src: enc('/assets/gallery/EvgenyGlobenko_Cup of Silence.jpg'),
    tags: ['evgenyglobenko'],
    year: '2024',
    size: '80×80 cm',
    mediumEn: 'Oil',
    mediumRu: 'Холст, масло',
    mediumEs: 'Óleo',
  },
  {
    id: 'evgenyglobenko-silence',
    artist: 'Evgeny Globenko',
    titleEn: 'Silence',
    titleRu: 'Тишина',
    titleEs: 'Silencio',
    src: enc('/assets/gallery/EvgenyGlobenko_Silence.jpg'),
    tags: ['evgenyglobenko'],
    year: '2024',
    size: '90×90 cm',
    mediumEn: 'Oil',
    mediumRu: 'Холст, масло',
    mediumEs: 'Óleo',
  },
  {
    id: 'joslen-orsini-1',
    artist: 'Joslen Orsini',
    titleEn: 'Inner Language I',
    titleRu: 'Внутренний язык I',
    titleEs: 'Lenguaje interno I',
    src: enc('/assets/gallery/Joslen_Orisini-1.jpg'),
    tags: ['joslenorsini'],
    year: '2024',
    size: '100×80 cm',
    mediumEn: 'Sculpture',
    mediumRu: 'Скульптура',
    mediumEs: 'Escultura',
  },
  {
    id: 'joslenorsini-fairytales',
    artist: 'Joslen Orsini',
    titleEn: 'Fairytales',
    titleRu: 'Сказки',
    titleEs: 'Cuentos de hadas',
    src: enc('/assets/gallery/JoslenOrsini_Fairytales.jpg'),
    tags: ['joslenorsini'],
    year: '2024',
    size: '120×100 cm',
    mediumEn: 'Sculpture',
    mediumRu: 'Скульптура',
    mediumEs: 'Escultura',
  },
  {
    id: 'joslenorsini-language',
    artist: 'Joslen Orsini',
    titleEn: 'Language',
    titleRu: 'Язык',
    titleEs: 'Lenguaje',
    src: enc('/assets/gallery/JoslenOrsini_Language.jpg'),
    tags: ['joslenorsini'],
    year: '2024',
    size: '80×120 cm',
    mediumEn: 'Sculpture',
    mediumRu: 'Скульптура',
    mediumEs: 'Escultura',
  },
  {
    id: 'joslenorsini-the-amazon-1',
    artist: 'Joslen Orsini',
    titleEn: 'The Amazon I',
    titleRu: 'Амазонка I',
    titleEs: 'El Amazonas I',
    src: enc('/assets/gallery/JoslenOrsini_The Amazon 1.jpg'),
    tags: ['joslenorsini'],
    year: '2024',
    size: '100×100 cm',
    mediumEn: 'Oil',
    mediumRu: 'Холст, масло',
    mediumEs: 'Óleo',
  },
  {
    id: 'joslenorsini-theuniverse',
    artist: 'Joslen Orsini',
    titleEn: 'The Universe',
    titleRu: 'Вселенная',
    titleEs: 'El universo',
    src: enc('/assets/gallery/JoslenOrsini_TheUniverse.jpg'),
    tags: ['joslenorsini'],
    year: '2024',
    size: '130×110 cm',
    mediumEn: 'Oil',
    mediumRu: 'Холст, масло',
    mediumEs: 'Óleo',
  },
  {
    id: 'omargodines-kantantab',
    artist: 'Omar Godines',
    titleEn: 'Kantanta B',
    titleRu: 'Кантанта B',
    titleEs: 'Cantata B',
    src: enc('/assets/gallery/OmarGodines_KantantaB.jpg'),
    tags: ['omargodines'],
    year: '2024',
    size: '70×90 cm',
    mediumEn: 'Oil',
    mediumRu: 'Холст, масло',
    mediumEs: 'Óleo',
  },
  {
    id: 'omargodines-serenada-i',
    artist: 'Omar Godines',
    titleEn: 'Serenada I',
    titleRu: 'Серенада I',
    titleEs: 'Serenata I',
    src: enc('/assets/gallery/OmarGodines_Serenada I.jpg'),
    tags: ['omargodines'],
    year: '2024',
    size: '80×100 cm',
    mediumEn: 'Oil',
    mediumRu: 'Холст, масло',
    mediumEs: 'Óleo',
  },
  {
    id: 'omargodines-serenada-ii',
    artist: 'Omar Godines',
    titleEn: 'Serenada II',
    titleRu: 'Серенада II',
    titleEs: 'Serenata II',
    src: enc('/assets/gallery/OmarGodines_Serenada II.jpg'),
    tags: ['omargodines'],
    year: '2024',
    size: '100×100 cm',
    mediumEn: 'Oil',
    mediumRu: 'Холст, масло',
    mediumEs: 'Óleo',
  },
  {
    id: 'omargodines-serenada-iii',
    artist: 'Omar Godines',
    titleEn: 'Serenada III',
    titleRu: 'Серенада III',
    titleEs: 'Serenata III',
    src: enc('/assets/gallery/OmarGodines_Serenada III.jpg'),
    tags: ['omargodines'],
    year: '2024',
    size: '90×80 cm',
    mediumEn: 'Oil',
    mediumRu: 'Холст, масло',
    mediumEs: 'Óleo',
  },
  {
    id: 'petertsvetkov-1',
    artist: 'Petr Tsvetkov',
    titleEn: 'Landscape I',
    titleRu: 'Пейзаж I',
    titleEs: 'Paisaje I',
    src: enc('/assets/gallery/PeterTsvetkov_1.jpg'),
    tags: ['petrtstvetkov'],
    year: '2024',
    size: '80×120 cm',
    mediumEn: 'Oil',
    mediumRu: 'Холст, масло',
    mediumEs: 'Óleo',
  },
  {
    id: 'petertsvetkov-2',
    artist: 'Petr Tsvetkov',
    titleEn: 'Landscape II',
    titleRu: 'Пейзаж II',
    titleEs: 'Paisaje II',
    src: enc('/assets/gallery/PeterTsvetkov_2.jpg'),
    tags: ['petrtstvetkov'],
    year: '2024',
    size: '100×100 cm',
    mediumEn: 'Oil',
    mediumRu: 'Холст, масло',
    mediumEs: 'Óleo',
  },
  {
    id: 'petertsvetkov-3',
    artist: 'Petr Tsvetkov',
    titleEn: 'Landscape III',
    titleRu: 'Пейзаж III',
    titleEs: 'Paisaje III',
    src: enc('/assets/gallery/PeterTsvetkov_3.jpg'),
    tags: ['petrtstvetkov'],
    year: '2024',
    size: '90×110 cm',
    mediumEn: 'Oil',
    mediumRu: 'Холст, масло',
    mediumEs: 'Óleo',
  },
  {
    id: 'petertsvetkov-4',
    artist: 'Petr Tsvetkov',
    titleEn: 'Landscape IV',
    titleRu: 'Пейзаж IV',
    titleEs: 'Paisaje IV',
    src: enc('/assets/gallery/PeterTsvetkov_4.jpg'),
    tags: ['petrtstvetkov'],
    year: '2024',
    size: '110×80 cm',
    mediumEn: 'Oil',
    mediumRu: 'Холст, масло',
    mediumEs: 'Óleo',
  },
  {
    id: 'thomasharutunyan-coldcorner',
    artist: 'Thomas Harutunyan',
    titleEn: 'Cold Corner',
    titleRu: 'Холодный угол',
    titleEs: 'Rincón frío',
    src: enc('/assets/gallery/ThomasHarutunyan_ColdCorner.jpg'),
    tags: ['thomasharutunyan'],
    year: '2024',
    size: '80×100 cm',
    mediumEn: 'Acrylic',
    mediumRu: 'Холст, акрил',
    mediumEs: 'Acrílico',
  },
  {
    id: 'thomasharutunyan-romeoandjuliet',
    artist: 'Thomas Harutunyan',
    titleEn: 'Romeo And Juliet',
    titleRu: 'Ромео и Джульетта',
    titleEs: 'Romeo y Julieta',
    src: enc('/assets/gallery/ThomasHarutunyan_RomeoAndJuliet.jpg'),
    tags: ['thomasharutunyan'],
    year: '2024',
    size: '100×120 cm',
    mediumEn: 'Mixed Media',
    mediumRu: 'Смешанная техника',
    mediumEs: 'Técnica mixta',
  },
  {
    id: 'thomasharutunyan-spontaniousresult',
    artist: 'Thomas Harutunyan',
    titleEn: 'Spontanious Result',
    titleRu: 'Спонтанный результат',
    titleEs: 'Resultado espontáneo',
    src: enc('/assets/gallery/ThomasHarutunyan_SpontaniousResult.jpg'),
    tags: ['thomasharutunyan'],
    year: '2024',
    size: '90×90 cm',
    mediumEn: 'Acrylic',
    mediumRu: 'Холст, акрил',
    mediumEs: 'Acrílico',
  },
  {
    id: 'thomasharutunyan-theeclipse',
    artist: 'Thomas Harutunyan',
    titleEn: 'The Eclipse',
    titleRu: 'Затмение',
    titleEs: 'El eclipse',
    src: enc('/assets/gallery/ThomasHarutunyan_TheEclipse.jpg'),
    tags: ['thomasharutunyan'],
    year: '2024',
    size: '110×100 cm',
    mediumEn: 'Mixed Media',
    mediumRu: 'Смешанная техника',
    mediumEs: 'Técnica mixta',
  },
];
