export type GalleryWork = {
  id: string;
  artist: string;
  titleEn: string;
  titleRu: string;
  src: string;
  tags: string[];
  year?: string;
  size?: string;
  medium?: string;
};

const enc = (path: string) => encodeURI(path);

export const galleryWorks: GalleryWork[] = [
  {
    id: 'andreyvaganov-breathofnature',
    artist: 'Andrey Vaganov',
    titleEn: 'Breath of Nature',
    titleRu: 'Дыхание природы',
    src: enc('/assets/gallery/AndreyVaganov_BreathofNature.jpg'),
    tags: ['andreyvaganov'],
    year: '2024',
    size: '100×100 cm',
    medium: 'холст',
  },
  {
    id: 'andreyvaganov-tellings',
    artist: 'Andrey Vaganov',
    titleEn: 'Tellings',
    titleRu: 'Сказания',
    src: enc('/assets/gallery/AndreyVaganov_Tellings.jpg'),
    tags: ['andreyvaganov'],
    year: '2024',
    size: '80×100 cm',
    medium: 'масло',
  },
  {
    id: 'andreyvaganov-thepath',
    artist: 'Andrey Vaganov',
    titleEn: 'The Path',
    titleRu: 'Путь',
    src: enc('/assets/gallery/AndreyVaganov_ThePath.jpg'),
    tags: ['andreyvaganov'],
    year: '2024',
    size: '120×80 cm',
    medium: 'акрил',
  },
  {
    id: 'andreyvaganov-theunityoftheuniverse',
    artist: 'Andrey Vaganov',
    titleEn: 'The Unity of The Universe',
    titleRu: 'Единство вселенной',
    src: enc('/assets/gallery/AndreyVaganov_TheUnityofTheUniverse.jpg'),
    tags: ['andreyvaganov'],
    year: '2024',
    size: '150×120 cm',
    medium: 'смешанная техника',
  },
  {
    id: 'evgenyglobenko-1',
    artist: 'Evgeny Globenko',
    titleEn: 'Void Fragment I',
    titleRu: 'Фрагмент пустоты I',
    src: enc('/assets/gallery/EvgenyGlobenko_1.jpg'),
    tags: ['evgenyglobenko'],
    year: '2024',
    size: '70×70 cm',
    medium: 'холст',
  },
  {
    id: 'evgenyglobenko-2',
    artist: 'Evgeny Globenko',
    titleEn: 'Void Fragment II',
    titleRu: 'Фрагмент пустоты II',
    src: enc('/assets/gallery/EvgenyGlobenko_2.jpg'),
    tags: ['evgenyglobenko'],
    year: '2024',
    size: '60×80 cm',
    medium: 'холст',
  },
  {
    id: 'evgenyglobenko-cup-of-silence',
    artist: 'Evgeny Globenko',
    titleEn: 'Cup of Silence',
    titleRu: 'Чаша тишины',
    src: enc('/assets/gallery/EvgenyGlobenko_Cup of Silence.jpg'),
    tags: ['evgenyglobenko'],
    year: '2024',
    size: '80×80 cm',
    medium: 'акрил',
  },
  {
    id: 'evgenyglobenko-silence',
    artist: 'Evgeny Globenko',
    titleEn: 'Silence',
    titleRu: 'Тишина',
    src: enc('/assets/gallery/EvgenyGlobenko_Silence.jpg'),
    tags: ['evgenyglobenko'],
    year: '2024',
    size: '90×90 cm',
    medium: 'смешанная техника',
  },
  {
    id: 'joslen-orsini-1',
    artist: 'Joslen Orsini',
    titleEn: 'Inner Language I',
    titleRu: 'Внутренний язык I',
    src: enc('/assets/gallery/Joslen_Orisini-1.jpg'),
    tags: ['joslenorsini'],
    year: '2024',
    size: '100×80 cm',
    medium: 'цифровое искусство',
  },
  {
    id: 'joslenorsini-fairytales',
    artist: 'Joslen Orsini',
    titleEn: 'Fairytales',
    titleRu: 'Сказки',
    src: enc('/assets/gallery/JoslenOrsini_Fairytales.jpg'),
    tags: ['joslenorsini'],
    year: '2024',
    size: '120×100 cm',
    medium: 'инсталляция',
  },
  {
    id: 'joslenorsini-language',
    artist: 'Joslen Orsini',
    titleEn: 'Language',
    titleRu: 'Язык',
    src: enc('/assets/gallery/JoslenOrsini_Language.jpg'),
    tags: ['joslenorsini'],
    year: '2024',
    size: '80×120 cm',
    medium: 'коллаж',
  },
  {
    id: 'joslenorsini-the-amazon-1',
    artist: 'Joslen Orsini',
    titleEn: 'The Amazon I',
    titleRu: 'Амазонка I',
    src: enc('/assets/gallery/JoslenOrsini_The Amazon 1.jpg'),
    tags: ['joslenorsini'],
    year: '2024',
    size: '100×100 cm',
    medium: 'акрил',
  },
  {
    id: 'joslenorsini-theuniverse',
    artist: 'Joslen Orsini',
    titleEn: 'The Universe',
    titleRu: 'Вселенная',
    src: enc('/assets/gallery/JoslenOrsini_TheUniverse.jpg'),
    tags: ['joslenorsini'],
    year: '2024',
    size: '130×110 cm',
    medium: 'смешанная техника',
  },
  {
    id: 'omargodines-kantantab',
    artist: 'Omar Godines',
    titleEn: 'Kantanta B',
    titleRu: 'Кантанта B',
    src: enc('/assets/gallery/OmarGodines_KantantaB.jpg'),
    tags: ['omargodines'],
    year: '2024',
    size: '70×90 cm',
    medium: 'акрил',
  },
  {
    id: 'omargodines-serenada-i',
    artist: 'Omar Godines',
    titleEn: 'Serenada I',
    titleRu: 'Серенада I',
    src: enc('/assets/gallery/OmarGodines_Serenada I.jpg'),
    tags: ['omargodines'],
    year: '2024',
    size: '80×100 cm',
    medium: 'масло',
  },
  {
    id: 'omargodines-serenada-ii',
    artist: 'Omar Godines',
    titleEn: 'Serenada II',
    titleRu: 'Серенада II',
    src: enc('/assets/gallery/OmarGodines_Serenada II.jpg'),
    tags: ['omargodines'],
    year: '2024',
    size: '100×100 cm',
    medium: 'смешанная техника',
  },
  {
    id: 'omargodines-serenada-iii',
    artist: 'Omar Godines',
    titleEn: 'Serenada III',
    titleRu: 'Серенада III',
    src: enc('/assets/gallery/OmarGodines_Serenada III.jpg'),
    tags: ['omargodines'],
    year: '2024',
    size: '90×80 cm',
    medium: 'акрил',
  },
  {
    id: 'petertsvetkov-1',
    artist: 'Petr Tsvetkov',
    titleEn: 'Landscape I',
    titleRu: 'Пейзаж I',
    src: enc('/assets/gallery/PeterTsvetkov_1.jpg'),
    tags: ['petrtstvetkov'],
    year: '2024',
    size: '80×120 cm',
    medium: 'акрил',
  },
  {
    id: 'petertsvetkov-2',
    artist: 'Petr Tsvetkov',
    titleEn: 'Landscape II',
    titleRu: 'Пейзаж II',
    src: enc('/assets/gallery/PeterTsvetkov_2.jpg'),
    tags: ['petrtstvetkov'],
    year: '2024',
    size: '100×100 cm',
    medium: 'акрил',
  },
  {
    id: 'petertsvetkov-3',
    artist: 'Petr Tsvetkov',
    titleEn: 'Landscape III',
    titleRu: 'Пейзаж III',
    src: enc('/assets/gallery/PeterTsvetkov_3.jpg'),
    tags: ['petrtstvetkov'],
    year: '2024',
    size: '90×110 cm',
    medium: 'масло',
  },
  {
    id: 'petertsvetkov-4',
    artist: 'Petr Tsvetkov',
    titleEn: 'Landscape IV',
    titleRu: 'Пейзаж IV',
    src: enc('/assets/gallery/PeterTsvetkov_4.jpg'),
    tags: ['petrtstvetkov'],
    year: '2024',
    size: '110×80 cm',
    medium: 'смешанная техника',
  },
  {
    id: 'thomasharutunyan-coldcorner',
    artist: 'Thomas Harutunyan',
    titleEn: 'Cold Corner',
    titleRu: 'Холодный угол',
    src: enc('/assets/gallery/ThomasHarutunyan_ColdCorner.jpg'),
    tags: ['thomasharutunyan'],
    year: '2024',
    size: '80×100 cm',
    medium: 'акрил',
  },
  {
    id: 'thomasharutunyan-romeoandjuliet',
    artist: 'Thomas Harutunyan',
    titleEn: 'Romeo And Juliet',
    titleRu: 'Ромео и Джульетта',
    src: enc('/assets/gallery/ThomasHarutunyan_RomeoAndJuliet.jpg'),
    tags: ['thomasharutunyan'],
    year: '2024',
    size: '100×120 cm',
    medium: 'смешанная техника',
  },
  {
    id: 'thomasharutunyan-spontaniousresult',
    artist: 'Thomas Harutunyan',
    titleEn: 'Spontanious Result',
    titleRu: 'Спонтанный результат',
    src: enc('/assets/gallery/ThomasHarutunyan_SpontaniousResult.jpg'),
    tags: ['thomasharutunyan'],
    year: '2024',
    size: '90×90 cm',
    medium: 'акрил',
  },
  {
    id: 'thomasharutunyan-theeclipse',
    artist: 'Thomas Harutunyan',
    titleEn: 'The Eclipse',
    titleRu: 'Затмение',
    src: enc('/assets/gallery/ThomasHarutunyan_TheEclipse.jpg'),
    tags: ['thomasharutunyan'],
    year: '2024',
    size: '110×100 cm',
    medium: 'масло',
  },
];
